### PR TITLE
LunarLander Implementation + Aether.Physics2D Integration + Updates

### PR DESCRIPTION
**Pull request by bojake**
This PR has updates to all of the nuget packages to get the project up to NetFramework 2.1. This leaves some problems with the Windows rendering engine.

This PR also has an implementation of the classic Lunar Lander (v2) environment. To implement Lunar Lander, I integrated the Aether.Physics2D engine. This engine was chosen over Box2D because it has more recent support from someone who is actively developing it.

There is a test case that implements the classic PID solver for Lunar Lander. This actually works. The rendering uses the Avalonia viewer, tested on Windows 11. 

This PR is a WIP. Expecting push back on style and lack of commenting and documentation. Wanted to get it out there for review.

Lunar Lander!!

### CODE REVIEW

**Comment by Nucs** [comment]
Nice work, will review till EOD

**Comment by Nucs** [comment]
Very nice work, much appreciated.
- I've added support for netcoreapp3.1 and net6.0 on master. Downgraded these changes to 6.0 (because its long-term support version).
- I've fixed up tests to run on all envs and added env.Close implementation.
- Reintroduced Avalonia's window sizing
I am missing an implementation of randomization seed. See the impl in CartpoleEnv

```C#
public override void Seed(int seed)
{
    throw new NotImplementedException();
}
```

Other than that, everything is top notch. I'll be merging and releasing a nuget after the required changes

**Comment by bojake** [comment]
Just note that the continuous mode is not implemented in this PR. I will work on that next.

**Comment by bojake** [comment]
I need my PR to numpy https://github.com/SciSharp/NumSharp/pull/489 so that I can setup consistency tests in lunar lander. The numpy seed is broken...

**Comment by Nucs** [comment]
I am afraid NumSharp hasn't been updated for a while nor can have a nuget released easily. You'll have to write a local function in this project to emulate np.choice behavior and call it from where you need.

**Comment by bojake** [comment]
This PR is complete now.

**Review by Nucs — APPROVED** [review]

**Pull request merged**
